<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared.Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\Shared.Application\Shared.Application.csproj" />
    <ProjectReference Include="..\Vorchestra.DTOs\Vorchestra.DTOs.csproj" />
    <ProjectReference Include="..\Vorchestra\Vorchestra.Domain.csproj" />
  </ItemGroup>

</Project>
